spin_manifest_version = 2

[application]
name = "bmonitor"
version = "0.1.0"
authors = ["Gabriel Fioravante <61801407+gabefiori@users.noreply.github.com>"]
description = ""

[variables]
public_api_key = { required = true }
private_api_key = { required = true }
cors_allowed_origins = { required = true }

[[trigger.http]]
route = "/..."
component = "bmonitor"

[component.bmonitor]
source = "main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.bmonitor.variables]
public_api_key = "{{ public_api_key }}"
private_api_key = "{{ private_api_key }}"
cors_allowed_origins = "{{ cors_allowed_origins }}"

[component.bmonitor.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
